SKALA-AXcalibur/AVALON

.gemini/config.yml
.gemini/styleguide.md

- Gemini Code Assist 설정(.env 검사하지 않도록 설정)
- Gemini Code Assist 스타일 가이드 작성(자바, 파이썬, 타입스크립트)

feat: Gemini Code Assist 설정

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/login/page.tsx
frontend/src/app/page.tsx
frontend/src/app/project/[project-id]/scenario/[scenario-id]/page.tsx
frontend/src/app/project/[project-id]/scenario/[scenario-id]/testcase/[testcase-id]/page.tsx
frontend/src/app/project/[project-id]/scenario/page.tsx
frontend/src/app/project/[project-id]/test-run/[scenario-id]/page.tsx
frontend/src/app/project/[project-id]/upload/page.tsx
frontend/src/components/common/Header.tsx
frontend/src/components/common/Sidebar.tsx
frontend/src/components/login/Login.tsx
frontend/src/components/scenario/ScenarioBox.tsx
frontend/src/components/test-run/TestRunMainTitle.tsx
frontend/src/components/test-run/TestRunSidebar.tsx
frontend/src/components/test-run/TestRunTable.tsx
frontend/src/components/testcase/TestcaseBox.tsx
frontend/src/components/testcase/TestcaseTable.tsx
frontend/src/components/upload/FileInputBox.tsx
frontend/src/components/upload/FileListItem.tsx
frontend/src/store/projectStore.ts
frontend/src/store/scenarioStore.ts
frontend/src/store/sidebarStore.ts
frontend/src/store/testcaseStore.ts

feat: 프론트엔드 초기 디자인 설정

---

frontend/.dockerignore
frontend/Dockerfile
frontend/README.md
frontend/next.config.ts

feat: front 빌드를 위한 설정 추가

---

frontend/src/app/project/[project-id]/upload/page.tsx
frontend/src/components/login/DeleteProjectButton.tsx
frontend/src/components/login/LoginProjectButton.tsx
frontend/src/components/login/ProjectIdInput.tsx
frontend/src/components/upload/UploadBox.tsx
frontend/src/constants/errorMessages.ts
frontend/src/constants/upload.ts
frontend/src/hooks/upload/createScenarios.ts
frontend/src/services/apiList.ts
frontend/src/services/scenario.ts
frontend/src/services/spec.ts
frontend/src/types/spec.d.ts
frontend/src/utils/ValidateId.ts
frontend/src/utils/validateFiles.ts

- 요구사항 명세서 업로드 ui 개발
- 시나리오 생성하기 요청 기능 개발
close #39

feat: 프론트엔드 명세서 업로드 페이지 개발

---

frontend/src/app/project/[project-id]/scenario/[scenario-id]/layout.tsx
frontend/src/app/project/[project-id]/scenario/[scenario-id]/testcase/[testcase-id]/page.tsx
frontend/src/components/common/TextInputBox.tsx
frontend/src/components/testcase/TestcaseBox.tsx
frontend/src/components/testcase/TestcaseDataTable.tsx
frontend/src/components/testcase/TestcaseNavigation.tsx
frontend/src/components/testcase/TestcaseTitle.tsx
frontend/src/hooks/testcase/createTestcase.ts
frontend/src/hooks/testcase/deleteTestcase.ts
frontend/src/hooks/testcase/readTestcase.ts
frontend/src/hooks/testcase/updateTestcase.ts
frontend/src/interfaces/testcase.ts
frontend/src/services/testcase.ts
frontend/src/types/testcase.d.ts

feat: 테스트케이스 출력 화면 개발

---

.gemini/styleguide.md

chore: gemini 스타일 가이드 수정

---

backend/spec/Dockerfile
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/controller/ProjectController.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/dto/ParameterDetailDto.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/dto/item/ColItem.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/dto/item/ParameterItem.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/DbColumnEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/service/ProjectServiceImpl.java

fix: 컨트롤러, DTO, 엔티티, ServiceImpl 일관화 관련 수정

---

frontend/mock-server/src/scenario.js
frontend/next.config.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/scenario/ScenarioGraph.tsx

feat: 시나리오 흐름도 출력 기능 개발

---

frontend/Dockerfile
frontend/src/app/api/health/route.ts
frontend/src/app/api/ready/route.ts

liveness - /api/health
readiness - /api/ready
close #20

feat: liveness readiness 추가

---

ai/Dockerfile

chore: 도커파일 추가

---

frontend/src/components/common/Sidebar.tsx
frontend/src/components/login/LoginProjectBox.tsx
frontend/src/components/scenario/ScenarioBox.tsx
frontend/src/components/test-run/TestRunBox.tsx
frontend/src/components/test-run/TestRunSidebar.tsx
frontend/src/components/test-run/TestRunTable.tsx
frontend/src/components/testcase/TestcaseBox.tsx
frontend/src/constants/messages.ts
frontend/src/constants/testStatus.ts
frontend/src/hooks/useProjectAuth.ts
frontend/src/hooks/useScenario.ts
frontend/src/hooks/useTestRun.ts
frontend/src/hooks/useTestcase.ts
frontend/src/store/sidebarStore.ts

feat: 프론트 기능 개선

---

backend/scenario/build.gradle
backend/scenario/src/main/java/com/sk/skala/axcalibur/feature/testcase/service/TcCommandServiceImpl.java
backend/scenario/src/main/java/com/sk/skala/axcalibur/global/config/UUIDConfig.java

feat tc id UUID v7로 수정

---

ai/Dockerfile

close #144 
- 도커파일에서 포트 80을 8080으로 변경

chore: 도커 포트 변경

---

backend/api-test/build.gradle
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/controller/ApiTestController.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/controller/ApiTestControllerImpl.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/service/ApiTestServiceImpl.java

close #149 
- IF-AT-0001 응답 수정
- 테스트 용 API 추가
- spring data jdbc 추가(빌드 실패 방지)

feat : API 테스트 응답 수정

---

backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/dto/item/ParameterItem.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/DbColumnEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/ParameterEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/service/ProjectServiceImpl.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/spec/client/AnalyzeSpecClient.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/spec/controller/ParseController.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/spec/controller/ParseControllerImpl.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/global/config/DataInitializerConfig.java

166 back bug 프로젝트 저장 참조 수정

---

ai/models/scenario.py

fix: 생성일시 필드 이름 수정 (created_at -> create_at)

---

backend/spec/src/main/java/com/sk/skala/axcalibur/spec/global/config/DataInitializerConfig.java

컨텍스트 데이터 COOKIE, SESSION 추가

---

backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/entity/TestcaseDataEntity.java

fix: TestcaseDataEntity의 value 타입을 text로 변경

---

backend/spec/src/main/java/com/sk/skala/axcalibur/spec/global/entity/ProjectEntity.java

cascade 리스트 추가

---

backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/controller/ApiTestController.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/controller/ApiTestControllerImpl.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/dto/request/ApiTaskDto.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/service/ApiTestServiceImpl.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/feature/util/ApiTaskDtoConverter.java
backend/api-test/src/main/java/com/sk/skala/axcalibur/apitest/global/config/ObjectMapperConfig.java
backend/api-test/src/test/java/com/sk/skala/axcalibur/apitest/feature/util/ApiTaskDtoConverterTest.java

close #196
- 홑따옴표 문자열을 처리하지 못하는 현상 해결
- 로깅 레벨을 변경해 오류 추적 개선

- fix : 역직렬화 문제 해결

---

backend/spec/src/main/java/com/sk/skala/axcalibur/spec/global/entity/ProjectEntity.java

Reverts SKALA-AXcalibur/AVALON#191

Revert "cascade 리스트 추가"

---

backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/ApiListEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/DbColumnEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/DbDesignEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/ParameterEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/project/entity/RequestEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/entity/MappingEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/entity/ScenarioEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/entity/TestCaseDataEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/entity/TestCaseEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/entity/TestcaseResultEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/repository/ScenarioRepository.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/repository/TestCaseRepository.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/service/ReportServiceImpl.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/global/entity/FilePathEntity.java
backend/spec/src/main/java/com/sk/skala/axcalibur/spec/global/entity/ProjectEntity.java

197 back feat backend spec cascade 연결 구조 재구성

---

backend/spec/src/main/java/com/sk/skala/axcalibur/spec/feature/report/entity/TestcaseResultEntity.java

result 컬럼 타입 TEXT로 변경
